sudo: required

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build --build-arg ORGANIZATION=$ORGANIZATION --build-arg SIMAGE_NAME=$IMAGE_NAME --build-arg CASADI_VERSION=$CASADI_VERSION -t rpi-debian-casadi .
  - docker tag rpi-debian-casadi $ORGANIZATION/rpi-debian-casadi:$CASADI_VERSION

script:
  - docker push $ORGANIZATION/rpi-debian-casadi:$CASADI_VERSION
